---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 7imbrook/ci-deploy-tools

inputs:
  - name: package

run:
  path: bash
  args:
    - -c
    - |
      set +x
      # I'm not happy about this :(
      echo "((s3.s3config))" | base64 -d > $HOME/.s3cfg
      s3cmd get s3://helm-charts/index.yaml
      helm repo index --merge index.yaml ./package
      s3cmd put -P index.yaml s3://helm-charts/index.yaml
