---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 7imbrook/ci-deploy-tools

inputs:
  - name: charts
  - name: ((version))

outputs:
  - name: package
    path: package

run:
  path: bash
  args:
    - -c
    - |
      version=$(cat ((version))/version)
      helm init --client-only
      echo "Packaging chart version $version..."
      helm package --version $version charts/((chart-path)) -d ./package
