---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 7imbrook/ci-deploy-tools

run:
  path: bash
  args:
    - -c
    - |
      echo "Verifying Helm chart from directory '((chart-path))'"
      ls -l ./charts/((chart-path))
      helm lint ./charts/((chart-path))
inputs:
  - name: charts
