apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-scripts
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
    entrypoint.sh: {{ tpl (.Files.Get "files/entrypoint.sh") . | quote }}