#!/bin/bash
set -e

source $(dirname $0)/common.sh

echo "Listing out available clusters"
token=$(cat $payload | jq '.source.token' -r)
doctl k8s cluster list -o json --access-token $token | jq 'map({"ref": .name })' >&3
