#!/bin/bash
set -e

source $(dirname $0)/common.sh

ACCESS_KEY=$(args | jq -r '.source.access_key_id')
SECRET_KEY=$(args | jq -r '.source.secret_access_key')

cat <<EOF >$HOME/.s3cfg
[default]
access_key = ${ACCESS_KEY} 
access_token = ${SECRET_KEY}
secret_key = ${SECRET_KEY}
bucket_location = sfo2
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
follow_symlinks = False
force = False
get_continue = False
gpg_command = None
host_base = sfo2.digitaloceanspaces.com
host_bucket = %(bucket)s.sfo2.digitaloceanspaces.com
human_readable_sizes = True
EOF

INDEX_DIR=$(args | jq -r '.params.artifacts')
cd $1/$INDEX_DIR

s3cmd get s3://helm-charts/index.yaml
helm repo index --merge index.yaml .
s3cmd put -P index.yaml s3://helm-charts/index.yaml

echo '{"version":{"ref":"none"}}' >&3
