---
resources:
  - name: charts
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/charts"
      branch: master
  - name: build-ci-environment
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/ci-deploy-tools
  - name: appshell-version
    type: semver
    source:
      driver: s3
      bucket: internal
      initial_version: 1.0.0
      key: versions/appshell
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))
  - name: release
    type: s3
    source:
      bucket: helm-charts
      regexp: appshell-(.*).tgz
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))

jobs:
  - name: Build Environment
    plan:
      - get: charts
        trigger: true
      - put: build-ci-environment
        params:
          build: charts/build_env
        get_params: { skip_download: true }
        inputs:
          - charts
  - name: Verify
    plan:
      - get: charts
        trigger: true
      - task: Verify
        file: charts/tasks/verify_chart.yaml
        vars:
          chart-path: appshell
  - name: Package Appshell Chart
    plan:
      - get: charts
        trigger: true
        passed:
          - Verify
      - get: appshell-version
        params:
          bump: patch
      - task: Package
        file: charts/tasks/package_chart.yaml
        vars:
          chart-path: appshell
          version: appshell-version
      - put: release
        params:
          file: "./package/*"
        inputs:
          - package
      - task: Index Release
        file: charts/tasks/index_chart.yaml
      - put: appshell-version
        params: { file: appshell-version/version }
