---
resource_types:
  - name: helm-indexer
    type: docker-image
    source:
      repository: 7imbrook/helm-indexer

resources:
  - name: charts
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/charts"
      branch: master
      ignore_paths:
        - appshell/*
        - vault/*
        - tasks/*
  - name: appshell
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/charts"
      branch: master
      paths:
        - appshell/*
        - tasks/*
  - name: vault
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/charts"
      branch: master
      paths:
        - vault/*
        - tasks/*
  - name: build-ci-environment
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/ci-deploy-tools
  - name: build-helm-indexer
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/helm-indexer
  - name: build-kube-auth
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/kube_authenticate
  - name: appshell-version
    type: semver
    source:
      driver: s3
      bucket: internal
      initial_version: 1.0.0
      key: versions/appshell
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))
  - name: vault-version
    type: semver
    source:
      driver: s3
      bucket: internal
      initial_version: 0.0.0
      key: versions/vault
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))
  - name: release-appshell
    type: s3
    source:
      bucket: helm-charts
      regexp: appshell-(.*).tgz
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))
  - name: release-vault
    type: s3
    source:
      bucket: helm-charts
      regexp: vault-(.*).tgz
      endpoint: sfo2.digitaloceanspaces.com
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))
  - name: chart-indexer
    type: helm-indexer
    source:
      bucket: helm-charts
      access_key_id: ((s3.id))
      secret_access_key: ((s3.key))

jobs:
  - name: Build Environment
    plan:
      - get: charts
        trigger: true
      - put: build-ci-environment
        params:
          build: charts/build_env
        get_params: { skip_download: true }
        inputs:
          - charts
  # Concourse Resources
  - name: Helm Indexer Resource Build
    plan:
      - get: charts
        trigger: true
      - put: build-helm-indexer
        params:
          build: charts/helm_indexer
        get_params: { skip_download: true }
        inputs:
          - charts
  - name: K8s Auth Resource Build
    plan:
      - get: charts
        trigger: true
      - put: build-kube-auth
        params:
          build: charts/kube_auth
        get_params: { skip_download: true }
        inputs:
          - charts
  # Helm Chart, Appshell
  - name: Verify Appshell
    plan:
      - get: appshell
        trigger: true
      - task: Verify
        file: appshell/tasks/verify_chart.yaml
        vars:
          name: appshell
          chart-path: appshell
  - name: Verify Vault
    plan:
      - get: vault
        trigger: true
      - task: Verify
        file: vault/tasks/verify_chart.yaml
        vars:
          name: vault
          chart-path: vault
  - name: Package Appshell Chart
    plan:
      - get: appshell
        trigger: true
        passed:
          - Verify Appshell
      - get: appshell-version
        params:
          bump: patch
      - task: Package
        file: appshell/tasks/package_chart.yaml
        vars:
          chart-path: appshell
          name: appshell
          version: appshell-version
      - put: release-appshell
        params:
          file: "./package/*"
          acl: public-read
        inputs:
          - package
      - put: chart-indexer
        params:
          artifacts: package
        inputs:
          - package
      - put: appshell-version
        params: { file: appshell-version/version }
  - name: Package Vault Chart
    plan:
      - get: vault
        trigger: true
        passed:
          - Verify Vault
      - get: vault-version
        params:
          bump: patch
      - task: Package
        file: vault/tasks/package_chart.yaml
        vars:
          name: vault
          chart-path: vault
          version: vault-version
      - put: release-vault
        params:
          file: "./package/*"
          acl: public-read
        inputs:
          - package
      - put: chart-indexer
        params:
          artifacts: package
        inputs:
          - package
      - put: vault-version
        params: { file: vault-version/version }
